tagline: "Final Year BCom/BCompSci Student @ Monash University"

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
livereload_ignore:
  - assets/
  - tools/
  - style.css

# disable smart quotes so its more just plain text
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 2..6