# Site settings
title: Nicholas Tay
email: nexerq@gmail.com
description: Does coding, clicks circles and goes to school all at once.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicholastay.github.io" # the base hostname & protocol for your site
twitter_username: n2468txd
github_username:  nicholastay
disqus_shortname: nexerq

# Build settings
markdown: kramdown
