# Site settings
title: Nexerq - aka n2468txd
email: nexerq@gmail.com
description: Just a guy who clicks circles, does coding, and goes to school all at once.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nexerq.cf" # the base hostname & protocol for your site
twitter_username: n2468txd
github_username:  n2468txd
osu_username: Nexerq

# Build settings
markdown: kramdown
