baseURL: https://nick.tay.blue/

params:
    name: Nicholas Tay
    tagline: "BCom/BCompSc Grad @ Monash University"

# I would prefer these on (I think) but CF pages is being dumb
uglyURLs: false

permalinks:
    post: "/:year/:month/:day/:slug"

frontmatter:
    # Pick up date from filename, which slug then becomes the part after filename
    date:
        - ":filename"
        - ":default"

outputs:
    section:
        - HTML
        - RSS

outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "rss"
