baseURL: https://nick.tay.blue/

params:
    name: Nicholas Tay
    navline: "Grad SRE @ IMC Trading | CS/Comm Grad @ Monash Uni"
    tagline: "Linux user messing with technologies including VMs, containers, networks and more."

# I would prefer these on (I think) but CF pages is being dumb
uglyURLs: false

permalinks:
    post: "/:year/:month/:day/:slug"

frontmatter:
    # Pick up date from filename, which slug then becomes the part after filename
    date:
        - ":filename"
        - ":default"

outputs:
    home:
        - HTML
        - RSS
    section:
        - HTML
    taxonomy:
        - HTML
    term:
        - HTML

outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "rss"
